[package]
name = "scylla-macros"
version = "0.1.2"
edition = "2021"
description = "proc macros for scylla async CQL driver"
repository = "https://github.com/scylladb/scylla-rust-driver"
readme = "../README.md"
categories = ["database"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0" 
proc-macro2 = "1.0"